FROM msoap/shell2http
# may be install some alpine packages:
# RUN apk add --no-cache ...
RUN apk update
RUN apk add dpkg
ADD https://dist.neo4j.org/cypher-shell/cypher-shell_4.1.2_all.deb /tmp
CMD dpkg -i /tmp/cypher-shell_4.1.2_all.deb
CMD ["/date", "date"] 
